### ISSUE TITLE
命名典故?

### ISSUE THREAD

**Issue by shyangs** [FloraCanou/january-font#1]
雲兒為什麼把這個字型命名為 January ?

**Comment by FloraCanou** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/January): 
> January (in Latin, Ianuarius) is named after the Latin word for door (ianua), since January is the door to the year and an opening to new beginnings. 
I take the symbol of beginning of my font design. 

根據[維基百科](https://en.wikipedia.org/wiki/January)：
一月在拉丁語中意為「門」，因為一月是一年之門，代表新的起始。
這裡取字體設計的起始之意。
